### ISSUE TITLE
ODataActionSample

### ISSUE THREAD

**Issue by HJoost** [xuzhg/WebApiSample#1]
Hi,

I just tried to follow your "ODataActionSample", but everytime I try to call the IsEmailAvailable Action with Fiddler I receive a 404:

http://localhost:33082/odata/Customers(3)/Extra.IsEmailAvailable
http://localhost:33082/odata/Customers/Extra.IsEmailAvailable

Can you please give me a hint what the correct URL's are, or even better include a readme with this information in the project.

Thanks!

Helmut

**Comment by xuzhg** [comment]
@HJoost 

I am happy that my sample can help you. And I am sorry for any inconvenient. 

To make it work, please modify `Web.Config` in project, change the `path` value form

```C#
<add name="ExtensionlessUrlHandler-Integrated-4.0" path="*/" verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
```

to

```C#
<add name="ExtensionlessUrlHandler-Integrated-4.0" path="*" verb="*" type="System.Web.Handlers.TransferRequestHandler" preCondition="integratedMode,runtimeVersionv4.0" />
```

I really appreciate to hear any further feedback from you.
Thanks.
Sam

**Comment by HJoost** [comment]
Hi,

thank you very much for your reply, especialy as you find only few information about this topic on the web.

I changed the Web.config as suggested now. Yet I get the following error:

{
  "error":{
    "code":"","message":"No HTTP resource was found that matches the request URI 'http://localhost:33082/odata/Customers/Default.IsEmailAvailable'.","innererror":{
      "message":"No routing convention was found to select an action for the OData path with template '~/entityset/action'.","type":"","stacktrace":""
    }
  }
}

Any ideas?

**Comment by xuzhg** [comment]
@HJoost 
Make sure the "namespace" of the action is correct. I think it should be  <strong>Extra</strong>

**Comment by HJoost** [comment]
Hi,

you are right. I tested some variations also with outcommenting the Namespace in the WebApiConfig.cs. But also with the original Files (of course with the change in the Web.config) and with Namespace Extra I get the same error:

{
  "error":{
    "code":"","message":"No HTTP resource was found that matches the request URI 'http://localhost:33082/odata/Customers(3)/Extra.IsEmailAvailable'.","innererror":{
      "message":"No routing convention was found to select an action for the OData path with template '~/entityset/key/action'.","type":"","stacktrace":""
    }
  }
}

{
  "error":{
    "code":"","message":"No HTTP resource was found that matches the request URI 'http://localhost:33082/odata/Customers/Extra.IsEmailAvailable'.","innererror":{
      "message":"No routing convention was found to select an action for the OData path with template '~/entityset/action'.","type":"","stacktrace":""
    }
  }
}

Perhaps it is an problem with IIS 10.0?

**Comment by xuzhg** [comment]
It's very strange. Everything works fine at my side. If possible, can we sync it with some remote desk?

**Comment by HJoost** [comment]
Due to our security policies in our company this is not possible. I will try your sample at home and if there is the same error i will post again, then we could do a remote session.

Thank you!!!

**Comment by xuzhg** [comment]
Never mind. Basically, I am available working days. Thanks.

**Comment by HJoost** [comment]
Hi,

finally I got it running:

When I edit the ExtensionLessURLHandelr the Internal Server Error on the Welcome Page of the WebApi stays there, but I don't need this page and everything else works fine. (This was a bit confusing, as I didn't realize that this error only belongs to (https://localhost:port)

The next problem was that I use [ODataRoutePrefix("tableName")] also as [ODataRoute("Default.ActionName")]. With this approach a URL like odata/tableName(1234)/Default.ActionName() seems not to be possible. Also I didn't find a solution for the URL like odata/tableName/Default.ActionName(1234). (1234 should be the ID of the Row I would like the Action to be affected on). So my solution is to use odata/tableName/Default.ActionName() and send the parameter via JSON Body.

Thank you!

Helmut

**Comment by xuzhg** [comment]
@HJoost. You are welcome.
