### ISSUE TITLE
Patch an entity with collection of complex type property doesn't work.

### ISSUE THREAD

**Issue by yuhong-l** [xuzhg/WebApiSample#5]
In file WebApiSample/v6.x/WebApi6xFeaturesTest/Complex/ComplexTypeTest.cs
Hi, in your test case, it worked because the outmost class Customer has key 'id', but it's nested object property 'Address' doesn't have.
**### If you try to add an 'Id' property for class 'Address', then the patch test will fail and get delta value is null.**
StatusCode: 400, ReasonPhrase: 'Bad Request'.
@xuzhg

**Comment by xuzhg** [comment]
@yuhong-l  what's your request Url string? In my memory, "Address" is a complex type, a complex type is a structural type which doesn't have a key.

**Comment by xuzhg** [comment]
Absolutely, OData supports this. 
Nested object (Aka, nested resource) is called navigation property.
A navigation property is a property, which type is an entity type or collection of entity type.
An entity type is a structural type which have a key. 

So, a structural type (entity type or complex type) may has properties. The property defined on type (which mean you can see the property in the metadata) is called "declared" property. An "Open" structural type may have other "un-delcared" properties (which you can't see in the metadata), which is call "dynamic" property.

When you patch a resource, the property in the PATCH request payload should be "declared" properties, however, if the type of such resource is open type, the request payload can have other "dynamic" properties.

Nested resource is supported in all version. Would you please give me a repo or a detail requirement?

**Comment by yuhong-l** [comment]
Thanks for your kindly elaboration.
You solved my problem. (I should use $ref instead of PATCH directly).
One more question, for " A navigation property can't be used in "PATCH". ",
Is "Delta<>class can be used to parse <entity with complex type> but not <entity with nested entity>" by design? (It supported both in an old version as mentioned here https://github.com/OData/WebApi/issues/135#issuecomment-287860458 )
If Delta<>class can be used to parse both of them, then we could handle relationship ourself instead of use '$ref'.

**Comment by xuzhg** [comment]
close it and file new issue if you have further concerns or issues.
