### ISSUE TITLE
Allow Deep Navigation 

### ISSUE THREAD

**Issue by JuncalLP** [xuzhg/WebApiSample#63]
Coming from https://stackoverflow.com/questions/78956264/asp-net-core-odata-8-allow-deep-navigation/78975768#78975768

First of all, thanks for your time @xuzhg  and the valuable code sample. 

While this convention

`/Services(15)/ArticleService(20)`

would be part of what we need here, the navigation shouldn't have a defined end, as stated on [odata2ts docs](https://odata2ts.github.io/docs/odata-client/the-main-service#navigation) and the [OData v4 spec](https://docs.oasis-open.org/odata/odata/v4.01/odata-v4.01-part2-url-conventions.html#sec_AddressingaProperty).

So we should support 

`/Services(15)/ArticleService(20)/Article`

or any other property present on ArticleService, even back to Service, and allow this to keep going indefinitely, not only to get properties but allow to call bound actions/functions i.e.

`/Services(15)/ArticleService(20)/Article/ArticleBoundFunction()`

This poses an obvious problem, seems somehow related to https://github.com/OData/AspNetCoreOData/issues/75

I'm missing something here? Is this feasible?

**Comment by xuzhg** [comment]
@JuncalLP See the updated in the sample. Let me know any questions/concerns.

**Comment by JuncalLP** [comment]
> @JuncalLP See the updated in the sample. Let me know any questions/concerns.

No questions/concerns, the sample achieves the goal and I think I understand how it's implemented. Much appreciated, will get back if I run into any trouble implementing on my project.
